// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class DefensorResources
{
        public const string achievement_heri_da_cidade = "CgkI-6Xj6cYDEAIQAg"; // <GPGSID>
        public const string leaderboard_lista_dos_maiores_defensores_da_terra = "CgkI-6Xj6cYDEAIQBw"; // <GPGSID>
        public const string achievement_o_heri_ruma_ao_infinito = "CgkI-6Xj6cYDEAIQCA"; // <GPGSID>
        public const string achievement_heri_do_planeta_terra = "CgkI-6Xj6cYDEAIQBQ"; // <GPGSID>
        public const string achievement_heri_da_rua = "CgkI-6Xj6cYDEAIQAA"; // <GPGSID>
        public const string achievement_heri_do_bairro = "CgkI-6Xj6cYDEAIQAQ"; // <GPGSID>
        public const string achievement_heri_nacional = "CgkI-6Xj6cYDEAIQAw"; // <GPGSID>

}

